In [1]:
a = [1, 2, 3, 4]
b = []
b.append(a)

In [2]:
a

[1, 2, 3, 4]

In [3]:
b

[[1, 2, 3, 4]]

In [4]:
a=[7, 8, 9]

In [5]:
b

[[1, 2, 3, 4]]

In [7]:
b.append(a.copy())

In [8]:
b

[[1, 2, 3, 4], [7, 8, 9]]

In [9]:
a = [0, 0, 0]

In [12]:
a[0] = 'lll'

In [18]:
import numpy as np
list(np.linspace(start=0.1, stop=1000, num=10000))

[0.1,
 0.2,
 0.3,
 0.4,
 0.5,
 0.6,
 0.7,
 0.7999999999999999,
 0.8999999999999999,
 0.9999999999999999,
 1.0999999999999999,
 1.2,
 1.3,
 1.4,
 1.5,
 1.5999999999999999,
 1.7,
 1.8,
 1.9,
 2.0,
 2.0999999999999996,
 2.1999999999999997,
 2.3,
 2.4,
 2.5,
 2.6,
 2.6999999999999997,
 2.8,
 2.9,
 3.0,
 3.0999999999999996,
 3.1999999999999997,
 3.3,
 3.4,
 3.5,
 3.5999999999999996,
 3.6999999999999997,
 3.8,
 3.9,
 3.9999999999999996,
 4.1,
 4.199999999999999,
 4.299999999999999,
 4.3999999999999995,
 4.499999999999999,
 4.6,
 4.699999999999999,
 4.799999999999999,
 4.8999999999999995,
 4.999999999999999,
 5.1,
 5.199999999999999,
 5.299999999999999,
 5.3999999999999995,
 5.499999999999999,
 5.599999999999999,
 5.699999999999999,
 5.799999999999999,
 5.8999999999999995,
 5.999999999999999,
 6.099999999999999,
 6.199999999999999,
 6.299999999999999,
 6.3999999999999995,
 6.499999999999999,
 6.599999999999999,
 6.699999999999999,
 6.799999999999999,
 6.8999999999999995,
 6.999999999999999,
 

In [107]:
from sklearn.neural_network import MLPRegressor

In [108]:
hidden_n = 5
model = MLPRegressor(hidden_layer_sizes = hidden_n)

In [109]:
import helpers

In [110]:
X, y = helpers.getfeatures('data/', 'ant-1.3')

In [111]:
model.fit(X,y)

D:\python\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=5, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [112]:
t1 = model.coefs_[0].flatten()

In [113]:
t2 = model.coefs_[1].flatten()

In [117]:
bias = model.intercepts_

w = model.coefs_

In [118]:
w

[array([[ 1.25908342e-01,  4.80809446e-02, -2.96123839e-02,
         -2.31150646e-01,  9.09634749e-02],
        [-4.84516892e-01,  5.08611340e-02, -3.43583042e-01,
          1.84134022e-01, -1.08332332e-01],
        [ 8.36884313e-02, -8.16966332e-02, -2.85795714e-01,
         -1.73779131e-01, -1.58185293e-01],
        [-1.51588552e-01,  8.55540587e-02,  1.81623173e-01,
          3.62314439e-01, -1.13408665e-01],
        [ 9.00467183e-02, -2.01882306e-01,  7.95409938e-02,
         -1.49698684e-01, -2.09168160e-01],
        [-5.36539699e-01, -2.19965816e-01,  4.27372817e-01,
          3.82789946e-01, -4.81780254e-01],
        [-3.23184783e-02, -9.30411107e-02,  5.83289476e-02,
         -2.12404886e-01, -9.92531839e-02],
        [-5.54424670e-03, -1.48636288e-01,  3.87215952e-01,
         -4.50395962e-01, -5.21393262e-01],
        [-3.16718884e-01, -9.75726536e-02, -2.99879122e-01,
          3.34996639e-01, -4.80607763e-01],
        [-2.65820159e-01,  1.51486034e-01, -4.67748427e-01,
    

In [119]:
w0 = model.coefs_[0]
w1 = model.coefs_[1]

In [120]:
w0

array([[ 1.25908342e-01,  4.80809446e-02, -2.96123839e-02,
        -2.31150646e-01,  9.09634749e-02],
       [-4.84516892e-01,  5.08611340e-02, -3.43583042e-01,
         1.84134022e-01, -1.08332332e-01],
       [ 8.36884313e-02, -8.16966332e-02, -2.85795714e-01,
        -1.73779131e-01, -1.58185293e-01],
       [-1.51588552e-01,  8.55540587e-02,  1.81623173e-01,
         3.62314439e-01, -1.13408665e-01],
       [ 9.00467183e-02, -2.01882306e-01,  7.95409938e-02,
        -1.49698684e-01, -2.09168160e-01],
       [-5.36539699e-01, -2.19965816e-01,  4.27372817e-01,
         3.82789946e-01, -4.81780254e-01],
       [-3.23184783e-02, -9.30411107e-02,  5.83289476e-02,
        -2.12404886e-01, -9.92531839e-02],
       [-5.54424670e-03, -1.48636288e-01,  3.87215952e-01,
        -4.50395962e-01, -5.21393262e-01],
       [-3.16718884e-01, -9.75726536e-02, -2.99879122e-01,
         3.34996639e-01, -4.80607763e-01],
       [-2.65820159e-01,  1.51486034e-01, -4.67748427e-01,
         2.86486734e-01

In [121]:
w1

array([[ 0.03252557],
       [ 0.71938775],
       [-0.48807864],
       [ 0.53945981],
       [ 0.50052763]])

In [122]:
X.shape

(125, 20)

In [123]:
hidden_n

5

In [124]:
w0.shape

(20, 5)

In [125]:
w1.shape

(5, 1)

In [126]:
bias

[array([-0.43836151,  0.47990537,  0.23965882,  0.07724271, -0.50916093]),
 array([-1.13096623])]

In [127]:
bias[1]

array([-1.13096623])

In [129]:
bias[0].shape

(5,)

In [130]:
bias[1].shape

(1,)

In [94]:
w1

array([[ 0.09660453],
       [-0.00363048],
       [ 0.0056133 ],
       [-0.23268301],
       [-0.06274498],
       [ 0.03717372],
       [-0.00562386],
       [-0.06559856],
       [-0.00201468],
       [ 0.10719674],
       [-0.06158048],
       [-0.01573678],
       [ 0.07370246],
       [-0.07529144],
       [ 0.21273488],
       [-0.18711215],
       [ 0.10040723],
       [-0.10773009],
       [-0.1968214 ],
       [-0.15916548],
       [ 0.19773169],
       [-0.04432286],
       [ 0.2237783 ],
       [-0.1893325 ],
       [-0.13508252],
       [ 0.05320161],
       [ 0.04973219],
       [-0.20523292],
       [-0.00332363],
       [-0.00788863],
       [ 0.11654333],
       [ 0.13577962],
       [ 0.01851337],
       [-0.23668937],
       [ 0.12709647],
       [ 0.12748798],
       [-0.14174578],
       [-0.12816367],
       [ 0.03918868],
       [-0.22833545],
       [ 0.02118341],
       [-0.12334753],
       [ 0.17887764],
       [ 0.13208427],
       [ 0.08972982],
       [-0

In [89]:
bias[0]

array([ 0.18114346, -0.04834262, -0.08059066, -0.15250811,  0.17303197,
        0.18364297, -0.01926938,  0.10375902, -0.01139907,  0.09185662,
        0.04214686, -0.17892834,  0.11177539,  0.19188417, -0.10873767,
        0.10538095, -0.1821836 , -0.03039233,  0.15345203,  0.19758437,
        0.00785696, -0.01993877,  0.12099335, -0.04214365, -0.21657987,
        0.05986334, -0.00532669, -0.19536837, -0.00671764, -0.19063943,
       -0.03279196, -0.00025074,  0.07034904, -0.19310758,  0.047111  ,
        0.00751994, -0.14751974, -0.22761772, -0.08103142,  0.18456027,
        0.01410436, -0.20150534,  0.10623707, -0.17839774, -0.01371973,
       -0.07399994, -0.20957553,  0.15969422,  0.18827281,  0.03571111,
       -0.00776059,  0.01255254, -0.11913222, -0.08373343,  0.13167069,
        0.06792055,  0.20219781,  0.18054739, -0.06397511,  0.21607286,
       -0.19735505,  0.12102982, -0.14220826,  0.09079136,  0.21363334,
       -0.04762183,  0.11618337,  0.20661714,  0.01742244,  0.06

In [90]:
bias[1]

array([-0.23191032])

In [40]:
t1

array([ 0.11874368,  0.00383004,  0.15001548, ..., -0.1941034 ,
       -0.13896362,  0.13229603])

In [41]:
t2

array([-0.04077783, -0.08699583,  0.1238278 , -0.14211302, -0.2273116 ,
       -0.09095407, -0.04191445,  0.03946413, -0.19479723, -0.07439789,
       -0.13010669, -0.19839343,  0.23732666,  0.19466953,  0.24188983,
       -0.22512336,  0.17817116,  0.19269525, -0.2228329 , -0.07457718,
        0.22301191, -0.1432222 , -0.05775213,  0.0121422 , -0.18237215,
        0.01907039,  0.1683269 ,  0.06720852,  0.01308084,  0.16664712,
       -0.14176675,  0.1333982 , -0.22412445,  0.14377794,  0.00081146,
       -0.15897255,  0.05648652, -0.08374871, -0.06007215, -0.20871998,
        0.06027955,  0.23905195, -0.02163514,  0.15600058,  0.16231382,
        0.11410755, -0.05061792, -0.06438419, -0.18376294,  0.14136715,
       -0.04734986,  0.08586117, -0.18548276,  0.21111621, -0.00034746,
       -0.06116591,  0.235489  , -0.17793274, -0.01230411,  0.0794081 ,
        0.14363717,  0.08048271,  0.2336887 , -0.05480293, -0.0855467 ,
       -0.24284182,  0.23296207,  0.22203704, -0.21299622,  0.15

In [42]:
t = np.concatenate((t1, t2))

In [43]:
t

array([ 0.11874368,  0.00383004,  0.15001548, ..., -0.17594943,
        0.12324477,  0.24406363])

In [22]:
isinstance(model, MLPRegressor)

True

In [1]:
path = '../results/1231/新建文件夹/'
f1 = 'FPA_test'
f2 = 'FPA_train'
algorithm = 'RandomForestRegressor'

In [2]:
import make_tables

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
from make_tables import counting

In [4]:
counting(path,f1,algorithm,1)

0 0 0.5844489600765002
0.5844489600765002
0 1 0.5844489600765002
0.5844489600765002
0 2 0.5844489600765002
0.5844489600765002
0 3 0.5844489600765002
0.5844489600765002
0 4 0.5844489600765002
0.5844489600765002
0 5 0.5844489600765002
0.5844489600765002
0 6 0.5844489600765002
0.5844489600765002
0 7 0.5844489600765002
0.5844489600765002
0 8 0.5844489600765002
0.5844489600765002
0 9 0.5844489600765002
0.5844489600765002
0 10 0.5844489600765002
0.5844489600765002
0 11 0.5844489600765002
0.5844489600765002
0 12 0.5844489600765002
0.5844489600765002
0 13 0.5844489600765002
0.5844489600765002
0 14 0.5844489600765002
0.5844489600765002
0 15 0.5844489600765002
0.5844489600765002
0 16 0.5844489600765002
0.5844489600765002
0 17 0.5844489600765002
0.5844489600765002
0 18 0.5844489600765002
0.5844489600765002
0 19 0.5844489600765002
0.5844489600765002
0 20 0.5844489600765002
0.5844489600765002
0 21 0.5844489600765002
0.5844489600765002
0 22 0.5844489600765002
0.5844489600765002
0 23 0.58444896007650

10 2 0.8438349285123479
0.8438349285123479
10 3 0.8438349285123479
0.8438349285123479
10 4 0.8438349285123479
0.8438349285123479
10 5 0.8438349285123479
0.8438349285123479
10 6 0.8438349285123479
0.8438349285123479
10 7 0.8438349285123479
0.8438349285123479
10 8 0.8438349285123479
0.8438349285123479
10 9 0.8438349285123479
0.8438349285123479
10 10 0.8438349285123479
0.8438349285123479
10 11 0.8438349285123479
0.8438349285123479
10 12 0.8438349285123479
0.8438349285123479
10 13 0.8438349285123479
0.8438349285123479
10 14 0.8438349285123479
0.8438349285123479
10 15 0.8438349285123479
0.8438349285123479
10 16 0.8438349285123479
0.8438349285123479
10 17 0.8438349285123479
0.8438349285123479
10 18 0.8438349285123479
0.8438349285123479
10 19 0.8438349285123479
0.8438349285123479
10 20 0.8438349285123479
0.8438349285123479
10 21 0.8438349285123479
0.8438349285123479
10 22 0.8438349285123479
0.8438349285123479
10 23 0.8438349285123479
0.8438349285123479
11 0 0.8550717186777029
0.85507171867770

0.5074020737327188
18 15 0.5074020737327188
0.5074020737327188
18 16 0.5074020737327188
0.5074020737327188
18 17 0.5074020737327188
0.5074020737327188
18 18 0.5074020737327188
0.5074020737327188
18 19 0.5074020737327188
0.5074020737327188
18 20 0.5074020737327188
0.5074020737327188
18 21 0.5074020737327188
0.5074020737327188
18 22 0.5074020737327188
0.5074020737327188
18 23 0.5074020737327188
0.5074020737327188
19 0 0.6728054298642534
0.6728054298642534
19 1 0.6728054298642534
0.6728054298642534
19 2 0.6728054298642534
0.6728054298642534
19 3 0.6728054298642534
0.6728054298642534
19 4 0.6728054298642534
0.6728054298642534
19 5 0.6728054298642534
0.6728054298642534
19 6 0.6728054298642534
0.6728054298642534
19 7 0.6728054298642534
0.6728054298642534
19 8 0.6728054298642534
0.6728054298642534
19 9 0.6728054298642534
0.6728054298642534
19 10 0.6728054298642534
0.6728054298642534
19 11 0.6728054298642534
0.6728054298642534
19 12 0.6728054298642534
0.6728054298642534
19 13 0.672805429864253

In [5]:
counting(path,f1,algorithm,2)

0 0 0.5844489600765002
0.5844489600765002
0 1 0.5844489600765002
0.5844489600765002
0 2 0.5844489600765002
0.5844489600765002
0 3 0.5844489600765002
0.5844489600765002
0 4 0.5844489600765002
0.5844489600765002
0 5 0.5844489600765002
0.5844489600765002
0 6 0.5844489600765002
0.5844489600765002
0 7 0.5844489600765002
0.5844489600765002
0 8 0.5844489600765002
0.5844489600765002
0 9 0.5844489600765002
0.5844489600765002
0 10 0.5844489600765002
0.5844489600765002
0 11 0.5844489600765002
0.5844489600765002
0 12 0.5844489600765002
0.5844489600765002
0 13 0.5844489600765002
0.5844489600765002
0 14 0.5844489600765002
0.5844489600765002
0 15 0.5844489600765002
0.5844489600765002
0 16 0.5844489600765002
0.5844489600765002
0 17 0.5844489600765002
0.5844489600765002
0 18 0.5844489600765002
0.5844489600765002
0 19 0.5844489600765002
0.5844489600765002
0 20 0.5844489600765002
0.5844489600765002
0 21 0.5844489600765002
0.5844489600765002
0 22 0.5844489600765002
0.5844489600765002
0 23 0.58444896007650

11 6 0.8550717186777029
0.8550717186777029
11 7 0.8550717186777029
0.8550717186777029
11 8 0.8550717186777029
0.8550717186777029
11 9 0.8550717186777029
0.8550717186777029
11 10 0.8550717186777029
0.8550717186777029
11 11 0.8550717186777029
0.8550717186777029
11 12 0.8550717186777029
0.8550717186777029
11 13 0.8550717186777029
0.8550717186777029
11 14 0.8550717186777029
0.8550717186777029
11 15 0.8550717186777029
0.8550717186777029
11 16 0.8550717186777029
0.8550717186777029
11 17 0.8550717186777029
0.8550717186777029
11 18 0.8550717186777029
0.8550717186777029
11 19 0.8550717186777029
0.8550717186777029
11 20 0.8550717186777029
0.8550717186777029
11 21 0.8550717186777029
0.8550717186777029
11 22 0.8550717186777029
0.8550717186777029
11 23 0.8550717186777029
0.8550717186777029
12 0 0.7058773712737128
0.7058773712737128
12 1 0.7058773712737128
0.7058773712737128
12 2 0.7058773712737128
0.7058773712737128
12 3 0.7058773712737128
0.7058773712737128
12 4 0.7058773712737128
0.70587737127371

0.6882677801724137
21 1 0.6882677801724137
0.6882677801724137
21 2 0.6882677801724137
0.6882677801724137
21 3 0.6882677801724137
0.6882677801724137
21 4 0.6882677801724137
0.6882677801724137
21 5 0.6882677801724137
0.6882677801724137
21 6 0.6882677801724137
0.6882677801724137
21 7 0.6882677801724137
0.6882677801724137
21 8 0.6882677801724137
0.6882677801724137
21 9 0.6882677801724137
0.6882677801724137
21 10 0.6882677801724137
0.6882677801724137
21 11 0.6882677801724137
0.6882677801724137
21 12 0.6882677801724137
0.6882677801724137
21 13 0.6882677801724137
0.6882677801724137
21 14 0.6882677801724137
0.6882677801724137
21 15 0.6882677801724137
0.6882677801724137
21 16 0.6882677801724137
0.6882677801724137
21 17 0.6882677801724137
0.6882677801724137
21 18 0.6882677801724137
0.6882677801724137
21 19 0.6882677801724137
0.6882677801724137
21 20 0.6882677801724137
0.6882677801724137
21 21 0.6882677801724137
0.6882677801724137
21 22 0.6882677801724137
0.6882677801724137
21 23 0.68826778017241

In [6]:
counting(path,f2,algorithm,1)

0 0 0.9423030303030304
0.9423030303030304
0 1 0.9423030303030304
0.9423030303030304
0 2 0.9423030303030304
0.9423030303030304
0 3 0.9423030303030304
0.9423030303030304
0 4 0.9423030303030304
0.9423030303030304
0 5 0.9423030303030304
0.9423030303030304
0 6 0.9423030303030304
0.9423030303030304
0 7 0.9423030303030304
0.9423030303030304
0 8 0.9423030303030304
0.9423030303030304
0 9 0.9423030303030304
0.9423030303030304
0 10 0.9423030303030304
0.9423030303030304
0 11 0.9423030303030304
0.9423030303030304
0 12 0.9423030303030304
0.9423030303030304
0 13 0.9423030303030304
0.9423030303030304
0 14 0.9423030303030304
0.9423030303030304
0 15 0.9423030303030304
0.9423030303030304
0 16 0.9423030303030304
0.9423030303030304
0 17 0.9423030303030304
0.9423030303030304
0 18 0.9423030303030304
0.9423030303030304
0 19 0.9423030303030304
0.9423030303030304
0 20 0.9423030303030304
0.9423030303030304
0 21 0.9423030303030304
0.9423030303030304
0 22 0.9423030303030304
0.9423030303030304
0 23 0.94230303030303

12 10 0.9141419002155836
0.9141419002155836
12 11 0.9141419002155836
0.9141419002155836
12 12 0.9141419002155836
0.9141419002155836
12 13 0.9141419002155836
0.9141419002155836
12 14 0.9141419002155836
0.9141419002155836
12 15 0.9141419002155836
0.9141419002155836
12 16 0.9141419002155836
0.9141419002155836
12 17 0.9141419002155836
0.9141419002155836
12 18 0.9141419002155836
0.9141419002155836
12 19 0.9141419002155836
0.9141419002155836
12 20 0.9141419002155836
0.9141419002155836
12 21 0.9141419002155836
0.9141419002155836
12 22 0.9141419002155836
0.9141419002155836
12 23 0.9141419002155836
0.9141419002155836
13 0 0.9328402452426401
0.9328402452426401
13 1 0.9328402452426401
0.9328402452426401
13 2 0.9328402452426401
0.9328402452426401
13 3 0.9328402452426401
0.9328402452426401
13 4 0.9328402452426401
0.9328402452426401
13 5 0.9328402452426401
0.9328402452426401
13 6 0.9328402452426401
0.9328402452426401
13 7 0.9328402452426401
0.9328402452426401
13 8 0.9328402452426401
0.93284024524264

22 10 0.8265799516008935
0.8265799516008935
22 11 0.8265799516008935
0.8265799516008935
22 12 0.8265799516008935
0.8265799516008935
22 13 0.8265799516008935
0.8265799516008935
22 14 0.8265799516008935
0.8265799516008935
22 15 0.8265799516008935
0.8265799516008935
22 16 0.8265799516008935
0.8265799516008935
22 17 0.8265799516008935
0.8265799516008935
22 18 0.8265799516008935
0.8265799516008935
22 19 0.8265799516008935
0.8265799516008935
22 20 0.8265799516008935
0.8265799516008935
22 21 0.8265799516008935
0.8265799516008935
22 22 0.8265799516008935
0.8265799516008935
22 23 0.8265799516008935
0.8265799516008935
23 0 0.8247896464085671
0.8247896464085671
23 1 0.8247896464085671
0.8247896464085671
23 2 0.8247896464085671
0.8247896464085671
23 3 0.8247896464085671
0.8247896464085671
23 4 0.8247896464085671
0.8247896464085671
23 5 0.8247896464085671
0.8247896464085671
23 6 0.8247896464085671
0.8247896464085671
23 7 0.8247896464085671
0.8247896464085671
23 8 0.8247896464085671
0.82478964640856

38 11 0.9255731225296444
0.9255731225296444
38 12 0.9255731225296444
0.9255731225296444
38 13 0.9255731225296444
0.9255731225296444
38 14 0.9255731225296444
0.9255731225296444
38 15 0.9255731225296444
0.9255731225296444
38 16 0.9255731225296444
0.9255731225296444
38 17 0.9255731225296444
0.9255731225296444
38 18 0.9255731225296444
0.9255731225296444
38 19 0.9255731225296444
0.9255731225296444
38 20 0.9255731225296444
0.9255731225296444
38 21 0.9255731225296444
0.9255731225296444
38 22 0.9255731225296444
0.9255731225296444
38 23 0.9255731225296444
0.9255731225296444
39 0 0.9567191664093148
0.9567191664093148
39 1 0.9567191664093148
0.9567191664093148
39 2 0.9567191664093148
0.9567191664093148
39 3 0.9567191664093148
0.9567191664093148
39 4 0.9567191664093148
0.9567191664093148
39 5 0.9567191664093148
0.9567191664093148
39 6 0.9567191664093148
0.9567191664093148
39 7 0.9567191664093148
0.9567191664093148
39 8 0.9567191664093148
0.9567191664093148
39 9 0.9567191664093148
0.956719166409314

In [7]:
counting(path,f2,algorithm,2)

0 0 0.9423030303030304
0.9423030303030304
0 1 0.9423030303030304
0.9423030303030304
0 2 0.9423030303030304
0.9423030303030304
0 3 0.9423030303030304
0.9423030303030304
0 4 0.9423030303030304
0.9423030303030304
0 5 0.9423030303030304
0.9423030303030304
0 6 0.9423030303030304
0.9423030303030304
0 7 0.9423030303030304
0.9423030303030304
0 8 0.9423030303030304
0.9423030303030304
0 9 0.9423030303030304
0.9423030303030304
0 10 0.9423030303030304
0.9423030303030304
0 11 0.9423030303030304
0.9423030303030304
0 12 0.9423030303030304
0.9423030303030304
0 13 0.9423030303030304
0.9423030303030304
0 14 0.9423030303030304
0.9423030303030304
0 15 0.9423030303030304
0.9423030303030304
0 16 0.9423030303030304
0.9423030303030304
0 17 0.9423030303030304
0.9423030303030304
0 18 0.9423030303030304
0.9423030303030304
0 19 0.9423030303030304
0.9423030303030304
0 20 0.9423030303030304
0.9423030303030304
0 21 0.9423030303030304
0.9423030303030304
0 22 0.9423030303030304
0.9423030303030304
0 23 0.94230303030303

0.9141419002155836
12 23 0.9141419002155836
0.9141419002155836
13 0 0.9328402452426401
0.9328402452426401
13 1 0.9328402452426401
0.9328402452426401
13 2 0.9328402452426401
0.9328402452426401
13 3 0.9328402452426401
0.9328402452426401
13 4 0.9328402452426401
0.9328402452426401
13 5 0.9328402452426401
0.9328402452426401
13 6 0.9328402452426401
0.9328402452426401
13 7 0.9328402452426401
0.9328402452426401
13 8 0.9328402452426401
0.9328402452426401
13 9 0.9328402452426401
0.9328402452426401
13 10 0.9328402452426401
0.9328402452426401
13 11 0.9328402452426401
0.9328402452426401
13 12 0.9328402452426401
0.9328402452426401
13 13 0.9328402452426401
0.9328402452426401
13 14 0.9328402452426401
0.9328402452426401
13 15 0.9328402452426401
0.9328402452426401
13 16 0.9328402452426401
0.9328402452426401
13 17 0.9328402452426401
0.9328402452426401
13 18 0.9328402452426401
0.9328402452426401
13 19 0.9328402452426401
0.9328402452426401
13 20 0.9328402452426401
0.9328402452426401
13 21 0.932840245242640

23 10 0.8247896464085671
0.8247896464085671
23 11 0.8247896464085671
0.8247896464085671
23 12 0.8247896464085671
0.8247896464085671
23 13 0.8247896464085671
0.8247896464085671
23 14 0.8247896464085671
0.8247896464085671
23 15 0.8247896464085671
0.8247896464085671
23 16 0.8247896464085671
0.8247896464085671
23 17 0.8247896464085671
0.8247896464085671
23 18 0.8247896464085671
0.8247896464085671
23 19 0.8247896464085671
0.8247896464085671
23 20 0.8247896464085671
0.8247896464085671
23 21 0.8247896464085671
0.8247896464085671
23 22 0.8247896464085671
0.8247896464085671
23 23 0.8247896464085671
0.8247896464085671
24 0 0.9455332353421524
0.9455332353421524
24 1 0.9455332353421524
0.9455332353421524
24 2 0.9455332353421524
0.9455332353421524
24 3 0.9455332353421524
0.9455332353421524
24 4 0.9455332353421524
0.9455332353421524
24 5 0.9455332353421524
0.9455332353421524
24 6 0.9455332353421524
0.9455332353421524
24 7 0.9455332353421524
0.9455332353421524
24 8 0.9455332353421524
0.94553323534215

0.9421791325318296
33 16 0.9421791325318296
0.9421791325318296
33 17 0.9421791325318296
0.9421791325318296
33 18 0.9421791325318296
0.9421791325318296
33 19 0.9421791325318296
0.9421791325318296
33 20 0.9421791325318296
0.9421791325318296
33 21 0.9421791325318296
0.9421791325318296
33 22 0.9421791325318296
0.9421791325318296
33 23 0.9421791325318296
0.9421791325318296
34 0 0.8106793498017087
0.8106793498017087
34 1 0.8106793498017087
0.8106793498017087
34 2 0.8106793498017087
0.8106793498017087
34 3 0.8106793498017087
0.8106793498017087
34 4 0.8106793498017087
0.8106793498017087
34 5 0.8106793498017087
0.8106793498017087
34 6 0.8106793498017087
0.8106793498017087
34 7 0.8106793498017087
0.8106793498017087
34 8 0.8106793498017087
0.8106793498017087
34 9 0.8106793498017087
0.8106793498017087
34 10 0.8106793498017087
0.8106793498017087
34 11 0.8106793498017087
0.8106793498017087
34 12 0.8106793498017087
0.8106793498017087
34 13 0.8106793498017087
0.8106793498017087
34 14 0.810679349801708

PermissionError: [Errno 13] Permission denied: '../results/1231/新建文件夹/FPA_train_counts2.csv'

In [30]:
import target_functions as tgf

In [31]:
values = [9, 2,0,3,5,3,7,3,2,7,9,24,124]

In [32]:
rank = tgf.bubbleSort(values)

In [33]:
rank

[2, 1, 8, 3, 5, 7, 4, 6, 9, 0, 10, 11, 12]

In [34]:
values

[0, 2, 2, 3, 3, 3, 5, 7, 7, 9, 9, 24, 124]

In [35]:
values

[0, 2, 2, 3, 3, 3, 5, 7, 7, 9, 9, 24, 124]

In [37]:
import numpy as np
t = np.array(values)

In [38]:
t

array([  0,   2,   2,   3,   3,   3,   5,   7,   7,   9,   9,  24, 124])

In [39]:
values

[0, 2, 2, 3, 3, 3, 5, 7, 7, 9, 9, 24, 124]

In [53]:
x = np.array([1, 2,3,4])
y = np.array([5,2,3,3])

In [45]:
0.3*x

array([0.3, 0.6, 0.9, 1.2])

In [46]:
0.4*y

array([2. , 0.8, 1.2, 1.2])

In [49]:
0.3*x+0.4*y

array([2.3, 1.4, 2.1, 2.4])

In [44]:
np.argmax(x+y)

3

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [55]:
scaler = MinMaxScaler()

In [58]:
t = scaler.fit_transform(x)

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [59]:
t = [10,20,30,5,6,7]

In [60]:
import random

In [70]:
x = random.choice(t)

In [72]:
m = np.array(t)

In [73]:
m

array([10, 20, 30,  5,  6,  7])

In [76]:
np.delete(m, 1)

array([10, 30,  5,  6,  7])

In [77]:
m

array([10, 20, 30,  5,  6,  7])