In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from MSDP import MSDP
from SSDP import SSDP
from BPNN import BPNN
import target_functions as tgf
import matplotlib.pyplot as plt
import csv
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import dictionaries
import ma


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
fileLists = dictionaries.get_filelists()

In [4]:
import helpers

In [7]:
path = 'data/'

In [8]:
X, y = helpers.getfeatures(path, fileLists[0][1])

In [9]:
X,y

(array([[11.        ,  4.        ,  2.        , ..., 34.54545455,
          3.        ,  1.2727    ],
        [14.        ,  1.        ,  1.        , ..., 16.85714286,
          6.        ,  1.6429    ],
        [ 3.        ,  2.        ,  0.        , ..., 17.33333333,
          1.        ,  0.6667    ],
        ...,
        [14.        ,  1.        ,  0.        , ..., 56.57142857,
         24.        ,  2.7857    ],
        [ 4.        ,  2.        ,  0.        , ..., 13.5       ,
          5.        ,  1.75      ],
        [27.        ,  1.        ,  0.        , ..., 18.22222222,
         11.        ,  1.4444    ]]),
 array([0., 2., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 2., 0., 0., 1.,
        0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 3., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0.,
        0., 0., 0., 0., 0., 0., 3., 1., 0., 0., 1., 0., 0., 0., 0., 0

In [11]:
model = SSDP(X=X, y=y, model=1, drawing=0, l=-20, u=20, soea=1)

In [13]:
model.run()

In [14]:
best_gen = np.argmin(model.problem.maxormins * model.obj_trace[:, 1])

In [15]:
best_gen

94

In [16]:
best_objV = model.obj_trace[best_gen, 1]

In [17]:
best_objV

0.8186666666666667

In [18]:
model.population

In [26]:
model.population.ObjV.shape

(100, 1)

In [31]:
model.population.ObjV.shape[0]

100

In [27]:
model.population.ObjV[10][0]

0.8109090909090909

In [28]:
model.population.Chrom.shape

(100, 21)

In [29]:
model.population.Chrom[10]

array([-15.19873566,  -6.42175449, -12.65944674, -13.28424204,
        14.79389722,  -1.72246934,  17.27942111,  16.43218511,
        -5.50686399,   2.32668427,   1.5738716 ,  19.67952618,
       -15.85492868, -19.1482081 ,  13.02924968, -15.00887393,
       -12.59222645,  -8.87512303, -19.24961495, -14.38429257,
       -14.99594055])

In [23]:
model.population.ObjV

array([[0.81406061],
       [0.808     ],
       [0.808     ],
       [0.81163636],
       [0.81236364],
       [0.80872727],
       [0.81381818],
       [0.8089697 ],
       [0.81260606],
       [0.81842424],
       [0.81090909],
       [0.81139394],
       [0.81042424],
       [0.81139394],
       [0.80848485],
       [0.81818182],
       [0.81187879],
       [0.81866667],
       [0.81139394],
       [0.8070303 ],
       [0.80727273],
       [0.81721212],
       [0.81284848],
       [0.81260606],
       [0.81018182],
       [0.80969697],
       [0.80727273],
       [0.81139394],
       [0.80921212],
       [0.81333333],
       [0.81212121],
       [0.81236364],
       [0.80945455],
       [0.81163636],
       [0.81042424],
       [0.8089697 ],
       [0.81793939],
       [0.81357576],
       [0.80945455],
       [0.80751515],
       [0.80678788],
       [0.81430303],
       [0.81139394],
       [0.80921212],
       [0.81163636],
       [0.80727273],
       [0.81793939],
       [0.806

In [25]:
model.population.Chrom

array([[ -6.56194125, -16.20799623,  -9.40909889, ..., -11.73209243,
        -17.86406293,  -2.73900907],
       [  9.60058342, -10.910152  ,  -5.19868634, ..., -13.68668802,
        -10.05923092, -18.62913923],
       [  9.20894159, -18.09918677,  -7.39698501, ..., -11.45337755,
         -7.73898832,   2.51712913],
       ...,
       [-17.73167271, -17.13493591, -14.49923435, ..., -19.55530922,
         -6.01925319,  17.8600805 ],
       [  7.70179467, -19.01246969, -11.95197167, ..., -19.48226728,
          1.68303758,  11.94528196],
       [ 18.15262376,  -7.43889575, -19.49193302, ..., -19.87775019,
         -8.68078657, -11.4495952 ]])

In [33]:
best_Chrom = []

In [34]:
for tmp_index in range(model.population.ObjV.shape[0]):
    if model.population.ObjV[tmp_index][0] == best_objV:
        best_Chrom.append(model.population.Chrom[tmp_index])

In [35]:
best_Chrom

[array([ 18.37080293,  -8.64834909,  -3.88800185, -15.10672304,
          9.77128801,  -0.98841351,  18.33058244,  14.1558333 ,
        -16.32410552,  -6.65034828,   0.45572764,  19.04975163,
        -11.07508632,   5.27820385,  -9.84235826,  -7.61767136,
        -17.85662739,   0.04758908, -17.05660088, -15.94662783,
         18.33611072])]